version: '3.8'

services:
  gcl:
    build:
      context: ./servico_GCL
      args:
        - NO_CACHE=1
    volumes:
      - ./servico_GCL/dicionario_legislacao.dic:/app/dicionario_legislacao.dic
    ports:
      - "5000:5000"

  aila:
    build:
      context: ./servico_AILA
      args:
        - NO_CACHE=1
    depends_on:
      - gcl
    entrypoint: ["/wait-for-it.sh", "gcl:5000", "--"]
    command: ["python", "app.py"]
    ports:
      - "5001:5001"