name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy-aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 using rsync
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          rsync -avz -e "ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no" --delete --exclude '.git' --exclude 'Logs' ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/AILA
          rm /tmp/deploy_key

      - name: Run startup.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/AILA/back_end
            chmod +x startup.sh
            ./startup.sh
